### ISSUE TITLE
look for webmention endpoint in <a> elements

### ISSUE THREAD

**Issue by kartikprabhu** [bear/ronkyuu#8]
webmention endpoints can also reside in a ```<a rel="webmention">``` link on the page.

**Comment by bear** [comment]
someplace since you filed this and all of the work we've done to improve the code... this has been fixed!

The test data here https://github.com/bear/ronkyuu/blob/master/tests/data/webmention_rocks_test_6.html has the `rel=webmention` as an `<a href />` and the TestEndpoint test is finding it.
